apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30001
  - name: fake-admin-http
    protocol: TCP
    port: 8888
  selector:
    app: apache
