---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-scale-b
  labels:
    name: node-js-scale-b
    app: node-js-scale-b
    version: '0.3'
    service: node-js-scale-ab
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node-js-scale-b
      app: node-js-scale-b
      version: '0.3'
      service: node-js-scale-ab
  template:
    metadata:
      labels:
        name: node-js-scale-b
        app: node-js-scale-b
        version: '0.3'
        service: node-js-scale-ab
    spec:
      containers:
      - name: node-js-scale
        image: jonbaier/pod-scaling:0.3
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
