- name: setup post eks provision
  hosts: all, localhost
  connection: local
  vars_files:
  - vars.yml

  tasks:
  - name: create gp2 storage class
    k8s:
      state: present
      src: storage-class.yaml
      context: "{{kube_context}}"

  - name: download helm tarball and unpack helm
    unarchive:
      src: https://storage.googleapis.com/kubernetes-helm/helm-v{{helm_version}}-{{ansible_system | lower}}-amd64.tar.gz
      dest: /usr/bin/
      remote_src: yes
      extra_opts:
        - '--strip-components'
        - '1'
        - "{{ansible_system | lower}}-amd64/helm"
      become: true

  - name: initialize helm and install and configure tiller
    block:
    - name: create tiller service account and cluster bindings
      k8s:
        state: present
        src: rbac-config.yaml
        context: "{{kube_context}}"

    - name: initialize helm and install/configure tiller
      command: helm init --wait --kube-context {{kube_context}} --service-account tiller
    when: tiller == "install"

  - name: initialize helm and upgrade tiller
    command: helm init --wait --kube-context {{kube_context}} --upgrade
    when: tiller == "upgrade"

  - name: initialize helm client
    command: helm init --kube-context {{kube_context}} --client-only
    when: tiller == "none"
