# Utilizes features up to config version 3.1
# Build images: docker-compose build --pull
# Run containers: docker-compose up
#TODO: security options in config; registry url in repo; https://docs.docker.com/compose/startup-order/; entrypoint override; https://docs.docker.com/compose/compose-file/#volumes, https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir; https://docs.docker.com/compose/compose-file/#volume-configuration-reference; https://docs.docker.com/compose/compose-file/#variable-substitution
version: '3'

services:
  builder:
    build:
      context: .
      dockerfile: 'Dockerfile.builder'
    image: 'image-builder:1.0'
    container_name: machine-shop-image-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/.
  validator:
    build:
      context: .
      dockerfile: 'Dockerfile.validator'
    image: 'image-validator:1.0'
    container_name: machine-shop-image-validator
    depends_on:
      - builder
  scanner:
    build:
      context: .
      dockerfile: 'Dockerfile.scanner'
    image: 'image-scanner:1.0'
    container_name: machine-shop-image-scanner
    depends_on:
      - validator
  publisher:
    build:
      context: .
      dockerfile: 'Dockerfile.publisher'
    image: 'image-publisher:1.0'
    container_name: machine-shop-image-publisher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - scanner
  metadata:
    build:
      context: .
      dockerfile: 'Dockerfile.metadata'
    image: 'image-metadata:1.0'
    container_name: machine-shop-image-metadata
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - publisher
