FW:
  dribble: 0.9
  shot: 1.0
  pass: 0.8
  tackle: 0.5
  block: 0.0
  intercept: 0.3
AM:
  dribble: 0.9
  shot: 0.8
  pass: 1.0
  tackle: 0.6
  block: 0.0
  intercept: 0.8
DM:
  dribble: 0.2
  shot: 0.1
  pass: 0.8
  tackle: 0.7
  block: 0.5
  intercept: 0.8
DF:
  dribble: 0.1
  shot: 0.0
  pass: 0.8
  tackle: 1.0
  block: 0.9
  intercept: 0.5
GK:
  punch: 1.0
  catch: 1.0
