apiVersion: v1
kind: Service
metadata:
  name: custom-svc
  labels:
    app: custom-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: custom-svc
  labels:
    app: custom-svc
subsets:
- addresses:
  - ip: 10.0.1.2 # ip address service can point to, like load balancer ip
    ports:
    - name: http
      port: 80
      protocol: HTTP
