apiVersion: v1
kind: Service
metadata:
  name: node-js
  labels:
    name: node-js
    app: node-js
    deployment: test
spec:
  type: LoadBalancer
  ports:
  - port: 90
    targetPort: 80
  selector:
    name: node-js
    app: node-js
    deplomyent: test
