---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js
  labels:
    name: node-js
    app: node-js
    deployment: test
spec:
  replicas: 3
  selector:
    matchLabels:
      name: node-js
      app: node-js
      deployment: test
  template:
    metadata:
      labels:
        name: node-js
        app: node-js
        deployments: test
    spec:
      containers:
      - name: node-js
        image: jonbaier/node-express-info:latest
        ports:
        - containerPort: 80
        livenessProbe:
          # http health check
          httpGet:
            path: /
            port: 80
          # exec health check
          exec:
            command:
            - /usr/bin/health/checkHttpService.sh
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          # http health check
          httpGet:
            path: /status/
            port: 80
          # tcp health check
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
