---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-scale
  labels:
    name: node-js-scale
    app: node-js-scale
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-js-scale
      app: node-js-scale
  template:
    metadata:
      labels:
        name: node-js-scale
        app: node-js-scale
    spec:
      containers:
      - name: node-js-scale
        image: jonbaier/pod-scaling:0.1
        ports:
        - containerPort: 80
