---
- name: provision azure vhd
  hosts: localhost
  become: yes

  tasks:
  - name: install lamp
    package:
      name: "{{ item }}"
      state: installed
    with_items:
    - httpd
    - mariadb
    - php
