---
- name: check for valid puppet task
  fail:
    msg: "Invalid task variable assignment. Must be one of agent, apply, deploy, or r10k."
  when: task != "agent" and task != "apply" and task != "deploy" and task != "r10k"

- include: puppet-{{task}}.yml
