---
- name: internet services
  hosts: serverb.lab.example.com
  become: true
  tasks:
  - name: install packages
    yum:
      name: "{{item}}"
      state: latest
    with_items:
    - httpd
    - firewalld
    - mariadb-server
    - php
    - php-mysql
  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
  - name: services enabled and running
    service:
      name: "{{item}}"
      enabled: true
      state: started
    with_items:
    - httpd
    - mariadb
    - firewalld
  - name: get test php page
    get_url:
      url: "http://materials.example.com/grading/var/www/html/index.php"
      dest: /var/www/html/index.php
      mode: 0644

- name: test
  hosts: localhost
  tasks:
  - name: connect to internet web server
    uri:
      url: http://serverb.lab.example.com
      status_code: 200
